/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: gabrielestefa (https://sketchfab.com/gabrielestefa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/by-the-north-sea-dae-final-assignment-4c99ca497b38464099e648d69a01b56b
title: By the North Sea [DAE Final Assignment]
*/

import React, { useRef, useState, Suspense } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF, Html, useProgress } from '@react-three/drei';
import * as THREE from 'three';
import { Vector3 } from 'three';

function Loader() {
  const { progress } = useProgress();
  return <Html center>{progress} % loaded</Html>;
}

export default function Model({ publicURL, position: { x, y, z } }) {
  const vec = new THREE.Vector3();
  const group = useRef();
  const { nodes, materials } = useGLTF(publicURL);
  // Set up state for the hovered and active state
  const [active, setActive] = useState(false);

  useFrame(({ camera }) => {
    group.current.position.lerp(new Vector3(x, y, z), 1);
  });

  return (
    <Suspense>
      <group
        ref={group}
        onClick={() => setActive(!active)}
        dispose={null}
        rotation={[0, Math.PI, 0]}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group scale={0.01}>
              <mesh
                geometry={nodes.final_Diorama_combined_trees2grass_0.geometry}
                material={materials.trees2grass}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2treesFern_YellowLeaves1_0
                    .geometry
                }
                material={materials.house_V2treesFern_YellowLeaves1}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1trimTextures_0.geometry
                }
                material={materials.house_V1trimTextures}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_canoe2canoe_tire_pulley_0
                    .geometry
                }
                material={materials.canoe2canoe_tire_pulley}
              />
              <mesh
                geometry={
                  nodes
                    .final_Diorama_combined_fishing_shackbuoysbuoys_rop_fish_MAT_0
                    .geometry
                }
                material={materials.fishing_shackbuoysbuoys_rop_fish_MAT}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_rock_0.geometry}
                material={materials.rock}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2trimTextures_0.geometry
                }
                material={materials.house_V2trimTextures}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_boat1BoatFinal_0.geometry
                }
                material={materials.fishing_boat1BoatFinal}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_woodPeer_0.geometry}
                material={materials.woodPeer}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_lighthousetrim_MAT_0.geometry
                }
                material={materials.lighthousetrim_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2windowChimeyPlanks_MAT_0
                    .geometry
                }
                material={materials.house_V2windowChimeyPlanks_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2pasted__trimTextures_0
                    .geometry
                }
                material={materials.house_V2pasted__trimTextures}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_shackbuoysnet_MAT_0
                    .geometry
                }
                material={materials.fishing_shackbuoysnet_MAT}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_dirtPath_0.geometry}
                material={materials.dirtPath}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2curtain_MAT_0.geometry
                }
                material={materials.house_V2curtain_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_shackglass_0.geometry
                }
                material={materials.fishing_shackglass}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_lighthouselighthouse_MAT_0
                    .geometry
                }
                material={materials.lighthouselighthouse_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2trash1trash_0.geometry
                }
                material={materials.house_V2trash1trash}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_shackfishingNet_MAT_0
                    .geometry
                }
                material={materials.fishing_shackfishingNet_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_treespineBranch_V2_0.geometry
                }
                material={materials.treespineBranch_V2}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_treesbark_0.geometry}
                material={materials.treesbark}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_lighthousewindVane_MAT_0.geometry
                }
                material={materials.lighthousewindVane_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2interior_MAT_0.geometry
                }
                material={materials.house_V2interior_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_shackshackRoof_MAT_0
                    .geometry
                }
                material={materials.fishing_shackshackRoof_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_standardSurface6_0.geometry
                }
                material={materials.standardSurface6}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1roofUnder_MAT_0.geometry
                }
                material={materials.house_V1roofUnder_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1roof_MAT_0.geometry
                }
                material={materials.house_V1roof_MAT}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_lambert1_0.geometry}
                material={materials.lambert1}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_boat1fish_0.geometry
                }
                material={materials.fishing_boat1fish}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_lighthouseglass_0.geometry
                }
                material={materials.lighthouseglass}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1redPlanks_MAT_0.geometry
                }
                material={materials.house_V1redPlanks_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2glass_MAT_0.geometry
                }
                material={materials.house_V2glass_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_lighthouselighthouseRoof_MAT_0
                    .geometry
                }
                material={materials.lighthouselighthouseRoof_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_fishing_shackshackWall_MAT_0
                    .geometry
                }
                material={materials.fishing_shackshackWall_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V2redPlanksLeaking_MAT_0
                    .geometry
                }
                material={materials.house_V2redPlanksLeaking_MAT}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1standardSurface14_0
                    .geometry
                }
                material={materials.house_V1standardSurface14}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_grass_0.geometry}
                material={materials.grass}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_trees2Fern_YellowLeaves1_0
                    .geometry
                }
                material={materials.trees2Fern_YellowLeaves1}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_rocks1basalticRock_MAT_0.geometry
                }
                material={materials.rocks1basalticRock_MAT}
              />
              <mesh
                geometry={nodes.final_Diorama_combined_sand1_0.geometry}
                material={materials.sand1}
              />
              <mesh
                geometry={
                  nodes.final_Diorama_combined_house_V1interior_MAT_0.geometry
                }
                material={materials.house_V1interior_MAT}
              />
            </group>
          </group>
        </group>
      </group>
    </Suspense>
  );
}

// useGLTF.preload('/scene.gltf');
