/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jesper Landin (https://sketchfab.com/JesperLandin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/emd-gp7-western-pacific-713-1c89cb9f2c224b78b6fea50f82e042c3
title: EMD GP7 Western Pacific 713
*/

import React, { useRef,useState } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export default function ModelComponent({ ...props }) {
  const vec = new THREE.Vector3();
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/emd_gp7_western_pacific_713/scene.gltf')
  // Set up state for the hovered and active state
  const [active, setActive] = useState(false);

  useFrame(({ camera }, delta) => {
    active ? vec.set(2, 0, 1.9) : vec.set(0, 0, 0.3);
    camera.fov = 50;
    camera.lookAt(0, 0, 0);
    camera.position.lerp(vec, 0.06);
    camera.updateProjectionMatrix();
  });

  return (<>
    <group ref={group} {...props} dispose={null} onClick={() => setActive(!active)}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.polySurface543_bogie_front_0.geometry} material={materials.bogie_front} />
          <mesh geometry={nodes.polySurface543_bogie_front_0_1.geometry} material={materials.bogie_front} />
          <mesh geometry={nodes.polySurface543_bogie_front_0_2.geometry} material={materials.bogie_front} />
          <mesh geometry={nodes.polySurface543_bogie_front_0_3.geometry} material={materials.bogie_front} />
          <mesh geometry={nodes.polySurface757_bogie_back_0.geometry} material={materials.bogie_back} />
          <mesh geometry={nodes.polySurface757_bogie_back_0_1.geometry} material={materials.bogie_back} />
          <mesh geometry={nodes.polySurface757_bogie_back_0_2.geometry} material={materials.bogie_back} />
          <mesh geometry={nodes.polySurface757_bogie_back_0_3.geometry} material={materials.bogie_back} />
          <mesh geometry={nodes.polySurface898_bogie_front_0.geometry} material={materials.bogie_front} />
          <mesh geometry={nodes.polySurface925_bogie_back_0.geometry} material={materials.bogie_back} />
          <mesh geometry={nodes.polySurface1003_leaf_spring_front_0.geometry} material={materials.leaf_spring_front} />
          <mesh geometry={nodes.polySurface1196_leaf_spring_back_0.geometry} material={materials.leaf_spring_back} />
          <mesh geometry={nodes.pCube65_underside_01_0.geometry} material={materials.underside_01} />
          <mesh geometry={nodes.pCylinder51_underside_01_0.geometry} material={materials.underside_01} />
          <mesh geometry={nodes.pCube68_underside_01_0.geometry} material={materials.underside_01} />
          <mesh geometry={nodes.pCube111_front_01_0.geometry} material={materials.front_01} />
          <mesh geometry={nodes.pCylinder69_front_01_0.geometry} material={materials.front_01} />
          <mesh geometry={nodes.pTorus8_front_01_0.geometry} material={materials.front_01} />
          <mesh geometry={nodes.pTorus8_front_01_0_1.geometry} material={materials.front_01} />
          <group position={[0, 0, -16.85]}>
            <mesh geometry={nodes.pCube121_underside_01_0.geometry} material={materials.underside_01} />
          </group>
          <mesh geometry={nodes.pCube122_underside_02_0.geometry} material={materials.underside_02} />
          <mesh geometry={nodes.sweep31_underside_02_0.geometry} material={materials.underside_02} />
          <mesh geometry={nodes.pCube166_hull_01_0.geometry} material={materials.hull_01} />
          <group position={[0, 0.31, 0]}>
            <mesh geometry={nodes.pCube167_hull_01_0.geometry} material={materials.hull_01} />
          </group>
          <mesh geometry={nodes.polySurface1517_hull_01_0.geometry} material={materials.hull_01} />
          <mesh geometry={nodes.pCube170_hull_01_0.geometry} material={materials.hull_01} />
          <mesh geometry={nodes.polySurface1690_Floor_upper_left_0.geometry} material={materials.Floor_upper_left} />
          <mesh geometry={nodes.polySurface1940_floor_01_0.geometry} material={materials.floor_01} />
          <mesh geometry={nodes.polySurface1952_Floor_upper_left_0.geometry} material={materials.Floor_upper_left} />
          <mesh geometry={nodes.polySurface2006_floor_upper_right_0.geometry} material={materials.floor_upper_right} />
          <mesh geometry={nodes.polySurface2028_floor_upper_right_0.geometry} material={materials.floor_upper_right} />
          <mesh geometry={nodes.pCube239_cabin_0.geometry} material={materials.cabin} />
          <mesh geometry={nodes.pCube245_cabin_0.geometry} material={materials.cabin} />
          <mesh geometry={nodes.polySurface1508_cabin_0.geometry} material={materials.cabin} />
          <group position={[1.08, 6.91, -2.72]}>
            <mesh geometry={nodes.pCube254_radiator_0.geometry} material={materials.radiator} />
          </group>
          <mesh geometry={nodes.MASH3_ReproMesh1_radiator_0.geometry} material={materials.radiator} />
          <mesh geometry={nodes.polySurface2261_hull_03_0.geometry} material={materials.hull_03} />
          <mesh geometry={nodes.polySurface2261_hull_03_0_1.geometry} material={materials.hull_03} />
          <group position={[1.71, 3.33, 0.49]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.polySurface2362_hull_02_0.geometry} material={materials.hull_02} />
          </group>
          <group position={[1.51, 6.69, 2.09]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.pPlane3_hull_02_0.geometry} material={materials.hull_02} />
          </group>
          <mesh geometry={nodes.pPlane6_hull_02_0.geometry} material={materials.hull_02} />
          <mesh geometry={nodes.sweep95_hull_02_0.geometry} material={materials.hull_02} />
          <mesh geometry={nodes.polySurface2665_hull_02_0.geometry} material={materials.hull_02} />
          <mesh geometry={nodes.pPlane13_hull_04_0.geometry} material={materials.hull_04} />
          <mesh geometry={nodes.polySurface2826_hull_04_0.geometry} material={materials.hull_04} />
          <mesh geometry={nodes.pPlane15_hull_04_0.geometry} material={materials.hull_04} />
          <mesh geometry={nodes.pPlane15_hull_04_0_1.geometry} material={materials.hull_04} />
          <mesh geometry={nodes.pCube565_hull_05_0.geometry} material={materials.hull_05} />
          <mesh geometry={nodes.polySurface3373_hull_05_0.geometry} material={materials.hull_05} />
          <mesh geometry={nodes.polySurface2666_hull_05_0.geometry} material={materials.hull_05} />
          <mesh geometry={nodes.pCube571_lambert20_0.geometry} material={materials.lambert20} />
          <mesh geometry={nodes.pCube572_lambert20_0.geometry} material={materials.lambert20} />
          <mesh geometry={nodes.polySurface3564_glass_0.geometry} material={materials.glass} />
          <mesh geometry={nodes.pCylinder152_interior_0.geometry} material={materials.interior} />
          <mesh geometry={nodes.polySurface3882_radiator_0.geometry} material={materials.radiator} />
        </group>
      </group>
    </group>
    <directionalLight position={[5, 5, 5]} />
  </>)
}

// useGLTF.preload('/scene.gltf')
